export const queryKeys = {
  GET_COMMENTS: 'GET_COMMENTS',
  GET_POSTS: 'GET_POSTS',
  GET_PRODUCT: 'GET_PRODUCT',
  GET_TODOS: 'GET_TODOS',
  GET_USER: 'GET_USER',
  INFINITE_PRODUCTS: 'INFINITE_PRODUCTS',
  SEARCH_POSTS: 'SEARCH_POSTS',
};
